// src/components/GalleryGrid.vue
<template>
  <section class="gallery-grid">
    <article v-for="photo in photos" :key="photo.id" class="gallery-card">
      <img :src="photo.image" :alt="photo.title" loading="lazy" />
      <div class="gallery-info">
        <div>
          <p class="location">{{ photo.location }}</p>
          <h3>{{ photo.title }}</h3>
        </div>
        <p class="description">{{ photo.description }}</p>
      </div>
    </article>
  </section>
</template>

<script setup>
defineProps({
  photos: {
    type: Array,
    required: true,
  },
})
</script>

<style scoped>
.gallery-grid {
  padding: 2rem;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}

.gallery-card {
  border-radius: 20px;
  overflow: hidden;
  background: #fff;
  box-shadow: 0 15px 45px rgba(15, 23, 42, 0.12);
  display: flex;
  flex-direction: column;
}

img {
  width: 100%;
  height: 240px;
  object-fit: cover;
}

.gallery-info {
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.location {
  margin: 0;
  text-transform: uppercase;
  font-size: 0.75rem;
  letter-spacing: 0.15em;
  color: #0ea5e9;
}

h3 {
  margin: 0.3rem 0 0;
}

.description {
  margin: 0;
  color: #475569;
}
</style>

// src/lib/components/GalleryGrid.svelte
<script lang="ts">
  import { scrollReveal } from '$lib/utils/scrollReveal'
  import type { GalleryPhoto } from '$lib/data/types'

  let { photos }: { photos: GalleryPhoto[] } = $props()
</script>

<section class="max-w-6xl mx-auto px-6 lg:px-12 py-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
  {#each photos as photo, i (photo.id)}
    <article
      class="rounded-2xl overflow-hidden bg-white shadow-sm hover:shadow-lg transition-all duration-300 flex flex-col group"
      use:scrollReveal={{ delay: (i % 3) * 100 }}
    >
      <div class="overflow-hidden relative">
        <img
          src={photo.image}
          alt={photo.title}
          loading="lazy"
          class="w-full h-60 object-cover transition-transform duration-500 group-hover:scale-105"
        />
        <div class="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
          <p class="text-white font-semibold text-sm m-0">{photo.location}</p>
        </div>
      </div>
      <div class="p-6 flex flex-col gap-2">
        <div>
          <p class="m-0 uppercase text-xs tracking-wider text-ocean-500 font-bold">{photo.location}</p>
          <h3 class="mt-1 mb-0 text-lg font-bold text-slate-900">{photo.title}</h3>
        </div>
        <p class="m-0 text-slate-500 text-sm leading-relaxed">{photo.description}</p>
      </div>
    </article>
  {/each}
</section>
