// src/components/LegalMarkdown.vue
<template>
  <section class="legal-wrapper">
    <article v-if="content" v-html="htmlContent" class="legal-content"></article>
    <p v-else class="loading">Loading document…</p>
  </section>
</template>

<script setup>
import { computed } from 'vue'
import { marked } from 'marked'

const props = defineProps({
  content: {
    type: String,
    default: '',
  },
})

const htmlContent = computed(() => (props.content ? marked.parse(props.content) : ''))
</script>

<style scoped>
.legal-wrapper {
  padding: 2rem;
  max-width: 760px;
  margin: 0 auto;
}

.legal-content :deep(h1),
.legal-content :deep(h2),
.legal-content :deep(h3) {
  margin-top: 1.5rem;
  color: #0f172a;
}

.legal-content :deep(p),
.legal-content :deep(li) {
  color: #334155;
  line-height: 1.7;
}

.loading {
  text-align: center;
}
</style>

// src/lib/components/LegalMarkdown.svelte
<script lang="ts">
  import { marked } from 'marked'

  let { content = '' }: { content: string } = $props()

  let htmlContent = $derived(content ? marked.parse(content) as string : '')
</script>

<section class="p-8 max-w-3xl mx-auto">
  {#if content}
    <article class="legal-content">
      {@html htmlContent}
    </article>
  {:else}
    <p class="text-center">Loading document…</p>
  {/if}
</section>

<style>
  @reference "../../app.css";
  .legal-content :global(h1),
  .legal-content :global(h2),
  .legal-content :global(h3) {
    @apply mt-6 text-slate-900;
  }
  .legal-content :global(p),
  .legal-content :global(li) {
    @apply text-slate-700 leading-relaxed;
  }
</style>
