// src/components/OperationsShowcase.vue
<template>
  <section class="operations">
    <div class="section-heading">
      <p class="eyebrow">Field operations</p>
      <h2>Live programs across the islands.</h2>
      <p>
        Each cleanup run combines municipal funding, CSR sponsors, and volunteer task forces. We publish outcomes within 48 hours.
      </p>
    </div>
    <div class="operation-grid">
      <article v-for="op in operations" :key="op.id" class="operation-card">
        <img :src="op.photo" :alt="`${op.beach} cleanup photo`" loading="lazy" />
        <div class="operation-meta">
          <p class="island">{{ op.island }}</p>
          <h3>{{ op.beach }}</h3>
          <p class="impact">{{ op.impact }}</p>
          <p class="type">{{ op.type }}</p>
          <p class="description">{{ op.description }}</p>
          <div class="partners">
            <span v-for="partner in op.partners" :key="partner" class="chip">{{ partner }}</span>
          </div>
        </div>
      </article>
    </div>
  </section>
</template>

<script setup>
import operations from '@/data/operations'
</script>

<style scoped>
.operations {
  padding: 3rem 2rem;
}

.operation-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 1.5rem;
}

.operation-card {
  border-radius: 24px;
  overflow: hidden;
  border: 1px solid rgba(15, 23, 42, 0.08);
  background: #fff;
  box-shadow: 0 15px 40px rgba(15, 23, 42, 0.08);
  display: flex;
  flex-direction: column;
}

img {
  width: 100%;
  height: 220px;
  object-fit: cover;
}

.operation-meta {
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}

.island {
  margin: 0;
  color: #0ea5e9;
  text-transform: uppercase;
  letter-spacing: 0.15em;
  font-size: 0.75rem;
}

.impact {
  margin: 0;
  font-weight: 700;
  color: #0f172a;
}

.type {
  margin: 0;
  color: #475569;
  font-size: 0.9rem;
}

.description {
  margin: 0.2rem 0 0;
  color: #475569;
}

.partners {
  margin-top: 0.8rem;
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
}

.chip {
  padding: 0.25rem 0.75rem;
  border-radius: 999px;
  background: #e0f2fe;
  color: #0369a1;
  font-size: 0.8rem;
  font-weight: 600;
}
</style>

// src/lib/components/OperationsShowcase.svelte
<script lang="ts">
  import { scrollReveal } from '$lib/utils/scrollReveal'
  import { data } from '$lib/data/types'

  const { operations } = data
</script>

<section class="py-20 lg:py-28 bg-slate-50">
  <div class="max-w-6xl mx-auto px-6 lg:px-12">
    <div class="text-center max-w-2xl mx-auto mb-14" use:scrollReveal={{ delay: 0 }}>
      <p class="uppercase tracking-[0.2em] text-sm text-ocean-600 font-bold mb-3">{operations.eyebrow}</p>
      <h2 class="text-[clamp(1.8rem,3.5vw,2.8rem)] font-extrabold text-slate-900 leading-tight">{operations.headline}</h2>
      <p class="text-lg text-slate-500 mt-4">
        {operations.body}
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      {#each operations.items as op, i (op.id)}
        <article
          class="rounded-2xl overflow-hidden bg-white shadow-sm hover:shadow-xl hover:-translate-y-1.5 transition-all duration-300 flex flex-col group"
          use:scrollReveal={{ delay: i * 150 }}
        >
          <div class="overflow-hidden">
            <img
              src={op.photo}
              alt="{op.beach} cleanup photo"
              loading="lazy"
              class="w-full h-56 object-cover transition-transform duration-500 group-hover:scale-105"
            />
          </div>
          <div class="p-6 flex flex-col gap-1 flex-1">
            <div class="flex items-center gap-2">
              <span class="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></span>
              <p class="m-0 text-ocean-600 uppercase tracking-wider text-xs font-bold">{op.island}</p>
            </div>
            <h3 class="m-0 text-lg font-bold text-slate-900">{op.beach}</h3>
            <p class="m-0 font-bold text-slate-700">{op.impact}</p>
            <p class="m-0 text-slate-500 text-sm">{op.type}</p>
            <p class="mt-1 mb-0 text-slate-500 text-sm leading-relaxed">{op.description}</p>
            <div class="mt-3 flex flex-wrap gap-2">
              {#each op.partners as partner}
                <span class="py-1 px-3 rounded-full bg-ocean-50 text-ocean-700 text-xs font-semibold">{partner}</span>
              {/each}
            </div>
          </div>
        </article>
      {/each}
    </div>
  </div>
</section>
